#!/bin/bash


MODE=Debug

if [ "A$1" != "A" ]
then
	MODE=$1	
fi

export PATH=/opt/st/stm32cubeide_1.19.0/plugins/com.st.stm32cube.ide.mcu.externaltools.gnu-tools-for-stm32.13.3.rel1.linux64_1.0.0.202410170706/tools/bin:$PATH

cmake -DCMAKE_TOOLCHAIN_FILE=cubeide-gcc.cmake -S ./ -B $MODE -G"Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug

