/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "common.h"
#include <stdio.h>
#include "clock.h"  /* Include il nostro modulo di gestione clock */
#include "log.h"    /* Include il sistema di logging */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
    int clock_status;
    int log_status;

    /* =========================================================================
     * INIZIALIZZAZIONE DEL SISTEMA DI CLOCK
     * =========================================================================
     *
     * IMPORTANTE: La prima cosa da fare all'avvio è configurare il clock!
     * Tutte le periferiche e i timing dipendono dalla configurazione del clock.
     *
     * Al reset, l'STM32F103 parte con HSI a 8 MHz. Noi lo portiamo a 72 MHz
     * usando HSE + PLL.
     */

    /* Configura il sistema di clock a 72 MHz */
    clock_status = SystemClock_Config();

    /* Verifica che la configurazione sia andata a buon fine */
    if (clock_status != CLOCK_OK)
    {
        /* Errore nella configurazione del clock!
         * Questo può accadere se:
         * - L'oscillatore esterno HSE non è presente o non funziona
         * - Il PLL non riesce a fare lock
         *
         * In un'applicazione reale, qui dovresti:
         * 1. Accendere un LED di errore
         * 2. Inviare un messaggio di debug via UART
         * 3. Tentare una configurazione fallback (es. rimanere su HSI a 8 MHz)
         * 4. Eventualmente resettare il sistema
         */

        /* Per ora, stampa un messaggio di errore e resta bloccato */
        if (clock_status == CLOCK_ERROR_HSE)
        {
            log_error("HSE non si avvia! Verifica il quarzo esterno");
        }
        else if (clock_status == CLOCK_ERROR_PLL)
        {
        	log_error("ERRORE: PLL non fa lock! Problema di configurazione");
        }

        /* Loop infinito in caso di errore */
        while(1);
    }

    /* =========================================================================
     * INIZIALIZZAZIONE DEL SISTEMA DI LOGGING
     * =========================================================================
     *
     * Inizializza il buffer circolare in RAM dedicata (2KB @ 0x20004800).
     * Il logging è thread-safe e interrupt-safe.
     */

    log_status = log_init();
    if (log_status != LOG_OK)
    {
        log_error("Inizializzazione sistema log fallita!");
        while(1);
    }

    /* Primo log: sistema avviato! */
    log_info("Sistema STM32F103 avviato con successo");

    /* Log della configurazione completata */
    log_info("Clock configurato a 72 MHz");
    log_debug("HSE: 8 MHz, PLL: x9, SYSCLK: 72 MHz");

    /* =========================================================================
     * MAIN LOOP
     * =========================================================================
     */

    /* Loop principale dell'applicazione */

    while(1)
    {

        /* Per ora, non facciamo altro - il micro rimane in idle */
    }

    /* Nota: questo punto non viene mai raggiunto perché il while(1) è infinito */
    return 0;
}
